/**
 * Relationship conditions and ordering as subqueries.
 *
 * Why subqueries instead of `include`:
 *
 * - Semantics. django-filter applies every filter as its own `.filter()` call,
 *   so two filters on a to-many relation each get their own join ("some order
 *   has code A" AND "some order has code B"). One shared `include` would demand
 *   a single related row matching both. An `IN (SELECT ...)` per filter
 *   reproduces Django.
 * - `isnull` across a relation needs LEFT JOIN semantics (rows with no related
 *   row match); with subqueries that is an explicit "no related row" branch.
 * - Isolation. Filters never add joins to the consumer's query, so they cannot
 *   change which associated rows are loaded, duplicate rows, or interact with
 *   Sequelize's `limit` + `include` subquery rewriting.
 *
 * The SQL is generated by Sequelize's own query generator (`selectQuery`),
 * which escapes every value; it is then embedded with `Sequelize.literal`.
 * No client input is ever concatenated into SQL.
 */

import { Op } from 'sequelize';
import { ConfigurationError } from '../errors/index.js';
import { columnOf, isSingleValued, paranoidClause } from './model.js';
import { sqlFor } from './sql.js';

/**
 * Per-query alias generator, so nested subqueries never collide.
 * @returns {{ next(): string }}
 */
export function createAliasGenerator() {
  let n = 0;
  return {
    next() {
      n += 1;
      return `__dsf${n}`;
    },
  };
}

function queryGenerator(model) {
  const qi = model?.sequelize?.getQueryInterface?.();
  if (!qi?.queryGenerator) {
    throw new ConfigurationError(`Model ${model?.name ?? '(unknown)'} is not attached to a Sequelize instance`);
  }
  return qi.queryGenerator;
}

function andAll(parts) {
  const present = parts.filter(Boolean);
  if (present.length === 0) return undefined;
  return present.length === 1 ? present[0] : { [Op.and]: present };
}

/**
 * `(SELECT column FROM table AS alias WHERE ...)` as a literal.
 * @param {object} model
 * @param {string} alias
 * @param {string|Array} column
 * @param {object} [where]
 * @param {{ limit?: number }} [options]
 */
function subselect(model, alias, column, where, options = {}) {
  const sql = queryGenerator(model).selectQuery(
    model.getTableName(),
    {
      attributes: [column],
      where: andAll([where, paranoidClause(model)]),
      tableAs: alias,
      ...(options.limit ? { limit: options.limit } : {}),
    },
    model,
  );
  return sqlFor(model).literal(`(${sql.replace(/;\s*$/, '')})`);
}

/**
 * Keys of an association, as column names.
 * @param {object} assoc
 */
function keysOf(assoc) {
  const source = assoc.source;
  const target = assoc.target;
  switch (assoc.associationType) {
    case 'BelongsTo':
      return {
        sourceCol: columnOf(source, assoc.foreignKey),
        targetCol: columnOf(target, assoc.targetKey),
        sourceNullable: source.getAttributes?.()[assoc.foreignKey]?.allowNull !== false,
      };
    case 'HasOne':
    case 'HasMany':
      return {
        sourceCol: columnOf(source, assoc.sourceKey),
        targetCol: columnOf(target, assoc.foreignKey),
        sourceNullable: false,
      };
    case 'BelongsToMany': {
      const through = assoc.through.model;
      return {
        sourceCol: columnOf(source, assoc.sourceKey),
        targetCol: columnOf(target, assoc.targetKey),
        through,
        throughSourceCol: columnOf(through, assoc.foreignKey),
        throughTargetCol: columnOf(through, assoc.otherKey),
        sourceNullable: false,
      };
    }
    default:
      throw new ConfigurationError(`Unsupported association type ${assoc.associationType}`);
  }
}

/**
 * The column on the root model through which a path is joined, and whether it
 * can be NULL (used by `exclude`).
 * @param {object} assoc first association of the path
 */
export function rootJoinColumn(assoc) {
  const { sourceCol, sourceNullable } = keysOf(assoc);
  return { column: sourceCol, nullable: sourceNullable };
}

/**
 * Condition on the source rows meaning "a row reached through `assoc`
 * (aliased `alias` in the subquery) satisfies `inner`".
 */
function exists(assoc, alias, inner, aliases) {
  const k = keysOf(assoc);
  if (assoc.associationType === 'BelongsToMany') {
    const targetIds = subselect(assoc.target, alias, k.targetCol, inner);
    const throughIds = subselect(k.through, aliases.next(), k.throughSourceCol, {
      [k.throughTargetCol]: { [Op.in]: targetIds },
    });
    return { [k.sourceCol]: { [Op.in]: throughIds } };
  }
  return { [k.sourceCol]: { [Op.in]: subselect(assoc.target, alias, k.targetCol, inner) } };
}

/** Condition meaning "no row is reached through `assoc`". */
function noneRelated(assoc, aliases) {
  const k = keysOf(assoc);
  if (assoc.associationType === 'BelongsTo') return { [k.sourceCol]: { [Op.is]: null } };
  if (assoc.associationType === 'BelongsToMany') {
    return {
      [k.sourceCol]: {
        [Op.notIn]: subselect(k.through, aliases.next(), k.throughSourceCol, {
          [k.throughSourceCol]: { [Op.not]: null },
        }),
      },
    };
  }
  return {
    [k.sourceCol]: {
      [Op.notIn]: subselect(assoc.target, aliases.next(), k.targetCol, { [k.targetCol]: { [Op.not]: null } }),
    },
  };
}

/**
 * Build a root-level condition for a filter on a related model.
 *
 * @param {object[]} associations path from the root model
 * @param {(model: object, alias: string) => object} leaf builds the condition
 *   on the final model; keys are column names, refs must be qualified by `alias`
 * @param {{ aliases: { next(): string }, nullMatches?: boolean, targetWhere?: object }} options
 *   `nullMatches` gives LEFT JOIN semantics (used for `isnull=true`): a row
 *   with no related row at some step also matches. `targetWhere` is ANDed into
 *   the final model's condition (ModelChoice `queryset`).
 */
export function relationCondition(associations, leaf, options) {
  const { aliases, nullMatches = false, targetWhere } = options;
  const build = (i) => {
    const assoc = associations[i];
    const alias = aliases.next();
    const inner = i === associations.length - 1 ? andAll([leaf(assoc.target, alias), targetWhere]) : build(i + 1);
    const cond = exists(assoc, alias, inner, aliases);
    return nullMatches ? { [Op.or]: [noneRelated(assoc, aliases), cond] } : cond;
  };
  return build(0);
}

/**
 * Collapse trailing belongs-to hops whose final attribute is the target key:
 * `company__id` is just `company_id` on the source (Django does the same).
 * @param {object[]} associations
 * @param {string} attribute
 * @returns {{ associations: object[], attribute: string }}
 */
export function collapseForeignKeys(associations, attribute) {
  const path = [...associations];
  let attr = attribute;
  while (path.length > 0) {
    const last = path[path.length - 1];
    if (last.associationType !== 'BelongsTo' || attr !== last.targetKey) break;
    attr = last.foreignKey;
    path.pop();
  }
  return { associations: path, attribute: attr };
}

/**
 * ORDER BY expression for a related attribute: a correlated scalar subquery.
 * Only single-valued paths (belongs-to / has-one) have one value per row.
 *
 * Unlike an `include`, this stays correct when Sequelize wraps the main query
 * in a subquery for `limit` + to-many includes.
 *
 * @param {object} model root model
 * @param {object[]} associations
 * @param {string} column final column name
 * @param {{ next(): string }} aliases
 */
export function orderingExpression(model, associations, column, aliases) {
  const build = (sourceAlias, i) => {
    const assoc = associations[i];
    if (!isSingleValued(assoc)) {
      throw new ConfigurationError(
        `Cannot order by a to-many relation ("${assoc.as}"): each row would have several values`,
      );
    }
    const k = keysOf(assoc);
    const alias = aliases.next();
    const selected = i === associations.length - 1 ? column : [build(alias, i + 1), 'v'];
    const where = { [k.targetCol]: { [Op.eq]: sqlFor(model).col(`${sourceAlias}.${k.sourceCol}`) } };
    return subselect(assoc.target, alias, selected, where, { limit: 1 });
  };
  return build(model.name, 0);
}
